### ISSUE TITLE
Ch 2.8 Question Wording

### ISSUE THREAD

**Issue by jpfasano** [RunestoneInteractive/thinkcspy#74] opened 2018-01-15 23:04 UTC
In Chapter 2.8 Input of _How To Think Like a Computer Scientist_ there is a question "Click on all of the variables of type `int` in the code below".

This question uses an undefined variable `total_secs`.
Since the variable is undefined, one can not know if it is of type int or not.

I believe the question should be rewritten as:
```python
seconds = input("Please enter the number of seconds you wish to convert")
total_secs = int(seconds)  # <--  This is a new line
hours = int(seconds) // 3600
secs_still_remaining = total_secs % 3600
print(secs_still_remaining)
```

The same problem exists with the subsequent question.
Here are the questions:
![image](https://user-images.githubusercontent.com/9619225/34964223-78c771a0-fa1a-11e7-9120-103b5371b201.png)

**Comment by bnmnetp** [comment] 2018-01-16 01:42
Thanks, this is a duplicate of RunestonServer#1080

I believe that line of code was accidentally deleted at some pont leaving the blank line in its place.

**Comment by bnmnetp** [comment] 2018-01-17 14:47
just merged the fix for this one.

**Closed by bnmnetp** 2018-01-17 14:47 UTC
Labels: good first issue, help wanted
