### ISSUE TITLE
Content Error?

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/thinkcspy#70] opened 2017-12-01 11:54 UTC
Error reported in course thinkcspy on page https://runestone.academy/runestone/static/thinkcspy/SimplePythonData/Input.html by user MiraclesHappen anto777dago@gmail.com
In the last exercise (2.8 Input)
Click on all of the variables of type `str` in the code below:

seconds = input("Please enter the number of seconds you wish to convert")
hours = int(seconds) // 3600
secs_still_remaining = total_secs % 3600
print(secs_still_remaining)

As far as I understand there are only 2 strings:
One is the input by the user which is stored in the variable called "seconds". The same variable is then used again to be converted into an integer and divided (//) by 3600. At this stage there are no other strings because the only string in the input has been converted into an integer. 
But then we find a variable called "total_secs" which seems to come out of the blue. I am no expert but I'm pretty sure there is a problem here!

**Comment by anujinm** [comment] 2018-01-19 21:56
It also seems like a duplicate of #1080 and it was merged 2 days ago.

**Closed** 2018-01-22 01:34 UTC
